In [4]:
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
dataset2002 = pd.read_excel('QBStats_2002_2003.xlsx',index_col=0)


dataset2002.head(1)

,Attempt,Completion,Yards,Yards per attempt,Touchdowns,Interceptions,Longest,Sack,Loss,QB Rating,Points,Year,Outcome
Quarterback,,,,,,,,,,,,,
Drew Brees,19,15,160,8.4,2,0,30,1,0,136.8,34,2002,W

In [5]:
dataset2002['Outcome_result'] = dataset2002.Outcome.map({'W':1, 'L':0})
dataset2002.head(10)
import matplotlib.pyplot as plt
import pandas as pd
from pandas.tools.plotting import table
dataset2002.head(5)

,Attempt,Completion,Yards,Yards per attempt,Touchdowns,Interceptions,Longest,Sack,Loss,QB Rating,Points,Year,Outcome,Outcome_result
Quarterback,,,,,,,,,,,,,,
Drew Brees,19,15,160,8.4,2,0,30,1,0,136.8,34,2002,W,1
Drew Bledsoe,39,26,271,6.9,1,2,52,4,29,73.8,31,2002,L,0
Peyton Manning,31,19,211,6.8,3,0,28,1,8,113.8,28,2002,W,1
Quincy Carter,30,13,131,4.4,0,1,31,3,19,42.5,10,2002,L,0
Tom Brady,43,29,294,6.8,3,0,40,2,14,110.0,30,2002,W,1

In [6]:
from sklearn import preprocessing 
import matplotlib.pyplot as plt
%matplotlib inline
plt.rc("font",size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns 
sns.set(style="white")
sns.set(style="whitegrid",color_codes=True)



print(dataset2002.shape)
print(list(dataset2002.columns))

(151, 14)
['Attempt', 'Completion', 'Yards', 'Yards per attempt', 'Touchdowns', 'Interceptions', 'Longest', 'Sack', 'Loss', 'QB Rating', 'Points', 'Year', 'Outcome', 'Outcome_result']

/Users/Vuongiie/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [7]:
#logistic regression

from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn import metrics 

cols = ["Attempt","Completion","Yards","Yards per attempt","Touchdowns","Interceptions","Sack","Loss",]
dataset_final2002 = dataset2002[cols]

X = dataset_final2002
Y = dataset2002["Outcome_result"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

log=LogisticRegression(penalty='l2',C=2)
log.fit(X_train,Y_train)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,log.predict(X_test))

0.8387096774193549

In [8]:
#Feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#fitting the Kernel SVM to the training split 
from sklearn.svm import SVC 
classifier = SVC(kernel = 'rbf', random_state=0)
classifier.fit(X_train, Y_train)

#Predicting the test set result 
y_pred = classifier.predict(X_test)

#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = Y_train, cv=10)
accuracies.mean()

0.7138694638694639

In [11]:
import pandas as pd 
dataset2016 = pd.read_excel('QBStats_2016.xlsx',index_col=0)
dataset2016['Outcome_result'] = dataset2016.Outcome.map({'W':1, 'L':0})
dataset2016.head(1)

,Attempt,Completion,Yards,Yards per attempt,Touchdowns,Interceptions,Longest,Sack,Loss,QB Rating,Points,Year,Outcome,Outcome_result
Quarterback,,,,,,,,,,,,,,
Jameis Winston,32,23,281,8.8,4,1,45,0,0,125.1,31,2016,W,1

In [12]:
#logistic regression

from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn import metrics 

cols2016 = ["Attempt","Completion","Yards","Yards per attempt","Touchdowns","Interceptions","Sack","Loss",]
dataset_final2016 = dataset2016[cols]



X_train = dataset_final2002
X_test = dataset_final2016
Y_train = dataset2002["Outcome_result"]
Y_test = dataset2016["Outcome_result"]

log=LogisticRegression(penalty='l2',C=2)
log.fit(X_train,Y_train)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,log.predict(X_test))

0.7682119205298014

In [13]:
#Feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#fitting the Kernel SVM to the training split 
from sklearn.svm import SVC 
classifier = SVC(kernel = 'rbf', random_state=0)
classifier.fit(X_train, Y_train)

#Predicting the test set result 
y_pred = classifier.predict(X_test)

#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

#Applying k-fold cross validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = Y_train, cv=10)
accuracies.mean()

0.7162499999999999