In [11]:
from sklearn import datasets
import pandas as pd

QB = pd.read_excel('QBStats_all_new.xlsx')

QB.head(8)

,Quarterback,Attempt,Completion,Yards,Yards per attempt,Touchdowns,Interceptions,Longest,Sack,Loss,QB Rating,Points,Home/Away,Year,Outcome
0,Drew Brees,19,15,160,8.4,2,0,30,1,0,136.8,34,away,2002,W
1,Drew Bledsoe,39,26,271,6.9,1,2,52,4,29,73.8,31,home,2002,L
2,Peyton Manning,31,19,211,6.8,3,0,28,1,8,113.8,28,away,2002,W
3,Quincy Carter,30,13,131,4.4,0,1,31,3,19,42.5,10,away,2002,L
4,Tom Brady,43,29,294,6.8,3,0,40t,2,14,110.0,30,home,2002,W
5,Peyton Manning,45,26,289,6.4,1,3,33,0,0,56.6,13,home,2002,L
6,Quincy Carter,24,14,240,10.0,2,0,44,1,10,120.1,21,home,2002,W
7,Tom Brady,35,25,269,7.7,2,1,49t,0,0,100.8,44,away,2002,W

In [15]:
print(QB.Outcome.head(5))
print(QB.Outcome.tail(5))

0    W
1    L
2    W
3    L
4    W
Name: Outcome, dtype: object
1209    L
1210    L
1211    W
1212    W
1213    W
Name: Outcome, dtype: object

In [36]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

columns = ['Attempt','Completion','Yards per attempt','Touchdowns','Interceptions','Sack']

X = QB[columns]
Y = QB['Outcome']

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=40) 


#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [37]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7654320987654321